<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Slideshow', 'doctrine');

/**
 * BaseSlideshow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idslideshow
 * @property string $file_name
 * @property string $body_h1
 * @property string $body_p
 * @property integer $publication
 * @property integer $default_position
 * @property string $body_link
 * @property Doctrine_Collection $BpcmsSlideshowI18n
 * 
 * @method integer             getIdslideshow()        Returns the current record's "idslideshow" value
 * @method string              getFileName()           Returns the current record's "file_name" value
 * @method string              getBodyH1()             Returns the current record's "body_h1" value
 * @method string              getBodyP()              Returns the current record's "body_p" value
 * @method integer             getPublication()        Returns the current record's "publication" value
 * @method integer             getDefaultPosition()    Returns the current record's "default_position" value
 * @method string              getBodyLink()           Returns the current record's "body_link" value
 * @method Doctrine_Collection getBpcmsSlideshowI18n() Returns the current record's "BpcmsSlideshowI18n" collection
 * @method Slideshow           setIdslideshow()        Sets the current record's "idslideshow" value
 * @method Slideshow           setFileName()           Sets the current record's "file_name" value
 * @method Slideshow           setBodyH1()             Sets the current record's "body_h1" value
 * @method Slideshow           setBodyP()              Sets the current record's "body_p" value
 * @method Slideshow           setPublication()        Sets the current record's "publication" value
 * @method Slideshow           setDefaultPosition()    Sets the current record's "default_position" value
 * @method Slideshow           setBodyLink()           Sets the current record's "body_link" value
 * @method Slideshow           setBpcmsSlideshowI18n() Sets the current record's "BpcmsSlideshowI18n" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlideshow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slideshow');
        $this->hasColumn('idslideshow', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('file_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('body_h1', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('body_p', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('default_position', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('body_link', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BpcmsSlideshowI18n', array(
             'local' => 'idslideshow',
             'foreign' => 'slideshow_idslideshow'));
    }
}