<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsAlbumMonthI18n', 'doctrine');

/**
 * BaseBpcmsAlbumMonthI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $album_month_idalbum_month
 * @property string $bpcms_lang_install_signature
 * @property string $lang_title
 * @property string $lang_description
 * @property BpcmsAlbumMonth $BpcmsAlbumMonth
 * @property BpcmsLangInstall $BpcmsLangInstall
 * 
 * @method integer             getAlbumMonthIdalbumMonth()       Returns the current record's "album_month_idalbum_month" value
 * @method string              getBpcmsLangInstallSignature()    Returns the current record's "bpcms_lang_install_signature" value
 * @method string              getLangTitle()                    Returns the current record's "lang_title" value
 * @method string              getLangDescription()              Returns the current record's "lang_description" value
 * @method BpcmsAlbumMonth     getBpcmsAlbumMonth()              Returns the current record's "BpcmsAlbumMonth" value
 * @method BpcmsLangInstall    getBpcmsLangInstall()             Returns the current record's "BpcmsLangInstall" value
 * @method BpcmsAlbumMonthI18n setAlbumMonthIdalbumMonth()       Sets the current record's "album_month_idalbum_month" value
 * @method BpcmsAlbumMonthI18n setBpcmsLangInstallSignature()    Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsAlbumMonthI18n setLangTitle()                    Sets the current record's "lang_title" value
 * @method BpcmsAlbumMonthI18n setLangDescription()              Sets the current record's "lang_description" value
 * @method BpcmsAlbumMonthI18n setBpcmsAlbumMonth()              Sets the current record's "BpcmsAlbumMonth" value
 * @method BpcmsAlbumMonthI18n setBpcmsLangInstall()             Sets the current record's "BpcmsLangInstall" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsAlbumMonthI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_album_month_i18n');
        $this->hasColumn('album_month_idalbum_month', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsAlbumMonth', array(
             'local' => 'album_month_idalbum_month',
             'foreign' => 'idbpcms_album_month'));

        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));
    }
}