<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsYtMoviesI18n', 'doctrine');

/**
 * BaseBpcmsYtMoviesI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bpcms_yt_movies_idbpcms_yt_movies
 * @property string $bpcms_lang_install_signature
 * @property string $lang_title
 * @property string $lang_description
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property BpcmsYtMovies $BpcmsYtMovies
 * 
 * @method integer           getBpcmsYtMoviesIdbpcmsYtMovies()      Returns the current record's "bpcms_yt_movies_idbpcms_yt_movies" value
 * @method string            getBpcmsLangInstallSignature()         Returns the current record's "bpcms_lang_install_signature" value
 * @method string            getLangTitle()                         Returns the current record's "lang_title" value
 * @method string            getLangDescription()                   Returns the current record's "lang_description" value
 * @method BpcmsLangInstall  getBpcmsLangInstall()                  Returns the current record's "BpcmsLangInstall" value
 * @method BpcmsYtMovies     getBpcmsYtMovies()                     Returns the current record's "BpcmsYtMovies" value
 * @method BpcmsYtMoviesI18n setBpcmsYtMoviesIdbpcmsYtMovies()      Sets the current record's "bpcms_yt_movies_idbpcms_yt_movies" value
 * @method BpcmsYtMoviesI18n setBpcmsLangInstallSignature()         Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsYtMoviesI18n setLangTitle()                         Sets the current record's "lang_title" value
 * @method BpcmsYtMoviesI18n setLangDescription()                   Sets the current record's "lang_description" value
 * @method BpcmsYtMoviesI18n setBpcmsLangInstall()                  Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsYtMoviesI18n setBpcmsYtMovies()                     Sets the current record's "BpcmsYtMovies" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsYtMoviesI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_yt_movies_i18n');
        $this->hasColumn('bpcms_yt_movies_idbpcms_yt_movies', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('BpcmsYtMovies', array(
             'local' => 'bpcms_yt_movies_idbpcms_yt_movies',
             'foreign' => 'idbpcms_yt_movies'));
    }
}