<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Gallery', 'doctrine');

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idgallery
 * @property string $file_name
 * @property string $file_title
 * @property integer $gallery_category_idgallery_category
 * @property string $redirect_to_url
 * @property integer $default_gallery
 * @property integer $default_gallery_off
 * @property integer $position_row
 * @property GalleryCategory $GalleryCategory
 * @property Doctrine_Collection $BpcmsGalleryI18n
 * 
 * @method integer             getIdgallery()                           Returns the current record's "idgallery" value
 * @method string              getFileName()                            Returns the current record's "file_name" value
 * @method string              getFileTitle()                           Returns the current record's "file_title" value
 * @method integer             getGalleryCategoryIdgalleryCategory()    Returns the current record's "gallery_category_idgallery_category" value
 * @method string              getRedirectToUrl()                       Returns the current record's "redirect_to_url" value
 * @method integer             getDefaultGallery()                      Returns the current record's "default_gallery" value
 * @method integer             getDefaultGalleryOff()                   Returns the current record's "default_gallery_off" value
 * @method integer             getPositionRow()                         Returns the current record's "position_row" value
 * @method GalleryCategory     getGalleryCategory()                     Returns the current record's "GalleryCategory" value
 * @method Doctrine_Collection getBpcmsGalleryI18n()                    Returns the current record's "BpcmsGalleryI18n" collection
 * @method Gallery             setIdgallery()                           Sets the current record's "idgallery" value
 * @method Gallery             setFileName()                            Sets the current record's "file_name" value
 * @method Gallery             setFileTitle()                           Sets the current record's "file_title" value
 * @method Gallery             setGalleryCategoryIdgalleryCategory()    Sets the current record's "gallery_category_idgallery_category" value
 * @method Gallery             setRedirectToUrl()                       Sets the current record's "redirect_to_url" value
 * @method Gallery             setDefaultGallery()                      Sets the current record's "default_gallery" value
 * @method Gallery             setDefaultGalleryOff()                   Sets the current record's "default_gallery_off" value
 * @method Gallery             setPositionRow()                         Sets the current record's "position_row" value
 * @method Gallery             setGalleryCategory()                     Sets the current record's "GalleryCategory" value
 * @method Gallery             setBpcmsGalleryI18n()                    Sets the current record's "BpcmsGalleryI18n" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('idgallery', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('file_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('file_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('gallery_category_idgallery_category', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('redirect_to_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('default_gallery', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('default_gallery_off', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('position_row', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GalleryCategory', array(
             'local' => 'gallery_category_idgallery_category',
             'foreign' => 'idgallery_category'));

        $this->hasMany('BpcmsGalleryI18n', array(
             'local' => 'idgallery',
             'foreign' => 'gallery_idgallery'));
    }
}