<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsLangText', 'doctrine');

/**
 * BaseBpcmsLangText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $text_name
 * @property string $text_value
 * @property Doctrine_Collection $BpcmsTextI18n
 * 
 * @method string              getTextName()      Returns the current record's "text_name" value
 * @method string              getTextValue()     Returns the current record's "text_value" value
 * @method Doctrine_Collection getBpcmsTextI18n() Returns the current record's "BpcmsTextI18n" collection
 * @method BpcmsLangText       setTextName()      Sets the current record's "text_name" value
 * @method BpcmsLangText       setTextValue()     Sets the current record's "text_value" value
 * @method BpcmsLangText       setBpcmsTextI18n() Sets the current record's "BpcmsTextI18n" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsLangText extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_lang_text');
        $this->hasColumn('text_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('text_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BpcmsTextI18n', array(
             'local' => 'text_name',
             'foreign' => 'bpcms_lang_text_text_name'));
    }
}