<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsYtCatalogI18n', 'doctrine');

/**
 * BaseBpcmsYtCatalogI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bpcms_yt_catalog_idbpcms_yt_catalog
 * @property string $bpcms_lang_install_signature
 * @property string $lang_name
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property BpcmsYtCatalog $BpcmsYtCatalog
 * 
 * @method integer            getBpcmsYtCatalogIdbpcmsYtCatalog()      Returns the current record's "bpcms_yt_catalog_idbpcms_yt_catalog" value
 * @method string             getBpcmsLangInstallSignature()           Returns the current record's "bpcms_lang_install_signature" value
 * @method string             getLangName()                            Returns the current record's "lang_name" value
 * @method BpcmsLangInstall   getBpcmsLangInstall()                    Returns the current record's "BpcmsLangInstall" value
 * @method BpcmsYtCatalog     getBpcmsYtCatalog()                      Returns the current record's "BpcmsYtCatalog" value
 * @method BpcmsYtCatalogI18n setBpcmsYtCatalogIdbpcmsYtCatalog()      Sets the current record's "bpcms_yt_catalog_idbpcms_yt_catalog" value
 * @method BpcmsYtCatalogI18n setBpcmsLangInstallSignature()           Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsYtCatalogI18n setLangName()                            Sets the current record's "lang_name" value
 * @method BpcmsYtCatalogI18n setBpcmsLangInstall()                    Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsYtCatalogI18n setBpcmsYtCatalog()                      Sets the current record's "BpcmsYtCatalog" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsYtCatalogI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_yt_catalog_i18n');
        $this->hasColumn('bpcms_yt_catalog_idbpcms_yt_catalog', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('BpcmsYtCatalog', array(
             'local' => 'bpcms_yt_catalog_idbpcms_yt_catalog',
             'foreign' => 'idbpcms_yt_catalog'));
    }
}