<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RadioStationI18n', 'doctrine');

/**
 * BaseRadioStationI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $radio_station_idradio_station
 * @property string $bpcms_lang_install_signature
 * @property string $lang_name
 * @property string $lang_title
 * @property string $lang_description
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property RadioStation $RadioStation
 * 
 * @method integer          getRadioStationIdradioStation()    Returns the current record's "radio_station_idradio_station" value
 * @method string           getBpcmsLangInstallSignature()     Returns the current record's "bpcms_lang_install_signature" value
 * @method string           getLangName()                      Returns the current record's "lang_name" value
 * @method string           getLangTitle()                     Returns the current record's "lang_title" value
 * @method string           getLangDescription()               Returns the current record's "lang_description" value
 * @method BpcmsLangInstall getBpcmsLangInstall()              Returns the current record's "BpcmsLangInstall" value
 * @method RadioStation     getRadioStation()                  Returns the current record's "RadioStation" value
 * @method RadioStationI18n setRadioStationIdradioStation()    Sets the current record's "radio_station_idradio_station" value
 * @method RadioStationI18n setBpcmsLangInstallSignature()     Sets the current record's "bpcms_lang_install_signature" value
 * @method RadioStationI18n setLangName()                      Sets the current record's "lang_name" value
 * @method RadioStationI18n setLangTitle()                     Sets the current record's "lang_title" value
 * @method RadioStationI18n setLangDescription()               Sets the current record's "lang_description" value
 * @method RadioStationI18n setBpcmsLangInstall()              Sets the current record's "BpcmsLangInstall" value
 * @method RadioStationI18n setRadioStation()                  Sets the current record's "RadioStation" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadioStationI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radio_station_i18n');
        $this->hasColumn('radio_station_idradio_station', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('RadioStation', array(
             'local' => 'radio_station_idradio_station',
             'foreign' => 'idradio_station'));
    }
}