<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsGalleryCategoryI18n', 'doctrine');

/**
 * BaseBpcmsGalleryCategoryI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gallery_category_idgallery_category
 * @property string $bpcms_lang_install_signature
 * @property string $lang_category_name
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property GalleryCategory $GalleryCategory
 * 
 * @method integer                  getGalleryCategoryIdgalleryCategory()    Returns the current record's "gallery_category_idgallery_category" value
 * @method string                   getBpcmsLangInstallSignature()           Returns the current record's "bpcms_lang_install_signature" value
 * @method string                   getLangCategoryName()                    Returns the current record's "lang_category_name" value
 * @method BpcmsLangInstall         getBpcmsLangInstall()                    Returns the current record's "BpcmsLangInstall" value
 * @method GalleryCategory          getGalleryCategory()                     Returns the current record's "GalleryCategory" value
 * @method BpcmsGalleryCategoryI18n setGalleryCategoryIdgalleryCategory()    Sets the current record's "gallery_category_idgallery_category" value
 * @method BpcmsGalleryCategoryI18n setBpcmsLangInstallSignature()           Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsGalleryCategoryI18n setLangCategoryName()                    Sets the current record's "lang_category_name" value
 * @method BpcmsGalleryCategoryI18n setBpcmsLangInstall()                    Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsGalleryCategoryI18n setGalleryCategory()                     Sets the current record's "GalleryCategory" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsGalleryCategoryI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_gallery_category_i18n');
        $this->hasColumn('gallery_category_idgallery_category', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_category_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('GalleryCategory', array(
             'local' => 'gallery_category_idgallery_category',
             'foreign' => 'idgallery_category'));
    }
}