<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GalleryToPost', 'doctrine');

/**
 * BaseGalleryToPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_idpost
 * @property integer $gallery_category_idgallery_category
 * @property GalleryCategory $GalleryCategory
 * @property Post $Post
 * 
 * @method integer         getId()                                  Returns the current record's "id" value
 * @method integer         getPostIdpost()                          Returns the current record's "post_idpost" value
 * @method integer         getGalleryCategoryIdgalleryCategory()    Returns the current record's "gallery_category_idgallery_category" value
 * @method GalleryCategory getGalleryCategory()                     Returns the current record's "GalleryCategory" value
 * @method Post            getPost()                                Returns the current record's "Post" value
 * @method GalleryToPost   setId()                                  Sets the current record's "id" value
 * @method GalleryToPost   setPostIdpost()                          Sets the current record's "post_idpost" value
 * @method GalleryToPost   setGalleryCategoryIdgalleryCategory()    Sets the current record's "gallery_category_idgallery_category" value
 * @method GalleryToPost   setGalleryCategory()                     Sets the current record's "GalleryCategory" value
 * @method GalleryToPost   setPost()                                Sets the current record's "Post" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGalleryToPost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery_to_post');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('post_idpost', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('gallery_category_idgallery_category', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GalleryCategory', array(
             'local' => 'gallery_category_idgallery_category',
             'foreign' => 'idgallery_category'));

        $this->hasOne('Post', array(
             'local' => 'post_idpost',
             'foreign' => 'idpost'));
    }
}