<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsYtCatalog', 'doctrine');

/**
 * BaseBpcmsYtCatalog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbpcms_yt_catalog
 * @property string $name
 * @property integer $publication
 * @property Doctrine_Collection $BpcmsYtCatalogI18n
 * @property Doctrine_Collection $BpcmsYtMovies
 * 
 * @method integer             getIdbpcmsYtCatalog()   Returns the current record's "idbpcms_yt_catalog" value
 * @method string              getName()               Returns the current record's "name" value
 * @method integer             getPublication()        Returns the current record's "publication" value
 * @method Doctrine_Collection getBpcmsYtCatalogI18n() Returns the current record's "BpcmsYtCatalogI18n" collection
 * @method Doctrine_Collection getBpcmsYtMovies()      Returns the current record's "BpcmsYtMovies" collection
 * @method BpcmsYtCatalog      setIdbpcmsYtCatalog()   Sets the current record's "idbpcms_yt_catalog" value
 * @method BpcmsYtCatalog      setName()               Sets the current record's "name" value
 * @method BpcmsYtCatalog      setPublication()        Sets the current record's "publication" value
 * @method BpcmsYtCatalog      setBpcmsYtCatalogI18n() Sets the current record's "BpcmsYtCatalogI18n" collection
 * @method BpcmsYtCatalog      setBpcmsYtMovies()      Sets the current record's "BpcmsYtMovies" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsYtCatalog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_yt_catalog');
        $this->hasColumn('idbpcms_yt_catalog', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BpcmsYtCatalogI18n', array(
             'local' => 'idbpcms_yt_catalog',
             'foreign' => 'bpcms_yt_catalog_idbpcms_yt_catalog'));

        $this->hasMany('BpcmsYtMovies', array(
             'local' => 'idbpcms_yt_catalog',
             'foreign' => 'bpcms_yt_catalog_idbpcms_yt_catalog'));
    }
}