<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsPostCatalogI18n', 'doctrine');

/**
 * BaseBpcmsPostCatalogI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_catalog_idpost_catalog
 * @property string $bpcms_lang_install_signature
 * @property string $lang_name
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property PostCatalog $PostCatalog
 * 
 * @method integer              getPostCatalogIdpostCatalog()     Returns the current record's "post_catalog_idpost_catalog" value
 * @method string               getBpcmsLangInstallSignature()    Returns the current record's "bpcms_lang_install_signature" value
 * @method string               getLangName()                     Returns the current record's "lang_name" value
 * @method BpcmsLangInstall     getBpcmsLangInstall()             Returns the current record's "BpcmsLangInstall" value
 * @method PostCatalog          getPostCatalog()                  Returns the current record's "PostCatalog" value
 * @method BpcmsPostCatalogI18n setPostCatalogIdpostCatalog()     Sets the current record's "post_catalog_idpost_catalog" value
 * @method BpcmsPostCatalogI18n setBpcmsLangInstallSignature()    Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsPostCatalogI18n setLangName()                     Sets the current record's "lang_name" value
 * @method BpcmsPostCatalogI18n setBpcmsLangInstall()             Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsPostCatalogI18n setPostCatalog()                  Sets the current record's "PostCatalog" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsPostCatalogI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_post_catalog_i18n');
        $this->hasColumn('post_catalog_idpost_catalog', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('PostCatalog', array(
             'local' => 'post_catalog_idpost_catalog',
             'foreign' => 'idpost_catalog'));
    }
}