<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PageBackup', 'doctrine');

/**
 * BasePageBackup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpage_backup
 * @property string $body
 * @property integer $page_idpage
 * @property string $created_at
 * @property Page $Page
 * 
 * @method integer    getIdpageBackup()  Returns the current record's "idpage_backup" value
 * @method string     getBody()          Returns the current record's "body" value
 * @method integer    getPageIdpage()    Returns the current record's "page_idpage" value
 * @method string     getCreatedAt()     Returns the current record's "created_at" value
 * @method Page       getPage()          Returns the current record's "Page" value
 * @method PageBackup setIdpageBackup()  Sets the current record's "idpage_backup" value
 * @method PageBackup setBody()          Sets the current record's "body" value
 * @method PageBackup setPageIdpage()    Sets the current record's "page_idpage" value
 * @method PageBackup setCreatedAt()     Sets the current record's "created_at" value
 * @method PageBackup setPage()          Sets the current record's "Page" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePageBackup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page_backup');
        $this->hasColumn('idpage_backup', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('page_idpage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Page', array(
             'local' => 'page_idpage',
             'foreign' => 'idpage'));
    }
}