<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Boxes', 'doctrine');

/**
 * BaseBoxes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idboxes
 * @property string $title
 * @property string $description
 * @property string $image
 * @property string $url_for_page
 * @property integer $publication
 * @property integer $position_row
 * @property integer $target
 * @property integer $show_homepage
 * @property integer $show_page
 * 
 * @method integer getIdboxes()       Returns the current record's "idboxes" value
 * @method string  getTitle()         Returns the current record's "title" value
 * @method string  getDescription()   Returns the current record's "description" value
 * @method string  getImage()         Returns the current record's "image" value
 * @method string  getUrlForPage()    Returns the current record's "url_for_page" value
 * @method integer getPublication()   Returns the current record's "publication" value
 * @method integer getPositionRow()   Returns the current record's "position_row" value
 * @method integer getTarget()        Returns the current record's "target" value
 * @method integer getShowHomepage()  Returns the current record's "show_homepage" value
 * @method integer getShowPage()      Returns the current record's "show_page" value
 * @method Boxes   setIdboxes()       Sets the current record's "idboxes" value
 * @method Boxes   setTitle()         Sets the current record's "title" value
 * @method Boxes   setDescription()   Sets the current record's "description" value
 * @method Boxes   setImage()         Sets the current record's "image" value
 * @method Boxes   setUrlForPage()    Sets the current record's "url_for_page" value
 * @method Boxes   setPublication()   Sets the current record's "publication" value
 * @method Boxes   setPositionRow()   Sets the current record's "position_row" value
 * @method Boxes   setTarget()        Sets the current record's "target" value
 * @method Boxes   setShowHomepage()  Sets the current record's "show_homepage" value
 * @method Boxes   setShowPage()      Sets the current record's "show_page" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBoxes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('boxes');
        $this->hasColumn('idboxes', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('url_for_page', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('position_row', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('target', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('show_homepage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('show_page', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}