<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GalleryToPage', 'doctrine');

/**
 * BaseGalleryToPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $page_idpage
 * @property integer $gallery_category_idgallery_category
 * @property GalleryCategory $GalleryCategory
 * @property Page $Page
 * 
 * @method integer         getId()                                  Returns the current record's "id" value
 * @method integer         getPageIdpage()                          Returns the current record's "page_idpage" value
 * @method integer         getGalleryCategoryIdgalleryCategory()    Returns the current record's "gallery_category_idgallery_category" value
 * @method GalleryCategory getGalleryCategory()                     Returns the current record's "GalleryCategory" value
 * @method Page            getPage()                                Returns the current record's "Page" value
 * @method GalleryToPage   setId()                                  Sets the current record's "id" value
 * @method GalleryToPage   setPageIdpage()                          Sets the current record's "page_idpage" value
 * @method GalleryToPage   setGalleryCategoryIdgalleryCategory()    Sets the current record's "gallery_category_idgallery_category" value
 * @method GalleryToPage   setGalleryCategory()                     Sets the current record's "GalleryCategory" value
 * @method GalleryToPage   setPage()                                Sets the current record's "Page" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGalleryToPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery_to_page');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('page_idpage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('gallery_category_idgallery_category', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GalleryCategory', array(
             'local' => 'gallery_category_idgallery_category',
             'foreign' => 'idgallery_category'));

        $this->hasOne('Page', array(
             'local' => 'page_idpage',
             'foreign' => 'idpage'));
    }
}