<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsPlaylist', 'doctrine');

/**
 * BaseBpcmsPlaylist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbpcms_playlist
 * @property integer $page_idpage
 * @property string $plate_title
 * @property string $plate_artist
 * @property string $plate_file
 * @property string $plate_cover
 * @property string $plate_buy_link
 * @property integer $publication
 * @property Page $Page
 * 
 * @method integer       getIdbpcmsPlaylist()  Returns the current record's "idbpcms_playlist" value
 * @method integer       getPageIdpage()       Returns the current record's "page_idpage" value
 * @method string        getPlateTitle()       Returns the current record's "plate_title" value
 * @method string        getPlateArtist()      Returns the current record's "plate_artist" value
 * @method string        getPlateFile()        Returns the current record's "plate_file" value
 * @method string        getPlateCover()       Returns the current record's "plate_cover" value
 * @method string        getPlateBuyLink()     Returns the current record's "plate_buy_link" value
 * @method integer       getPublication()      Returns the current record's "publication" value
 * @method Page          getPage()             Returns the current record's "Page" value
 * @method BpcmsPlaylist setIdbpcmsPlaylist()  Sets the current record's "idbpcms_playlist" value
 * @method BpcmsPlaylist setPageIdpage()       Sets the current record's "page_idpage" value
 * @method BpcmsPlaylist setPlateTitle()       Sets the current record's "plate_title" value
 * @method BpcmsPlaylist setPlateArtist()      Sets the current record's "plate_artist" value
 * @method BpcmsPlaylist setPlateFile()        Sets the current record's "plate_file" value
 * @method BpcmsPlaylist setPlateCover()       Sets the current record's "plate_cover" value
 * @method BpcmsPlaylist setPlateBuyLink()     Sets the current record's "plate_buy_link" value
 * @method BpcmsPlaylist setPublication()      Sets the current record's "publication" value
 * @method BpcmsPlaylist setPage()             Sets the current record's "Page" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsPlaylist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_playlist');
        $this->hasColumn('idbpcms_playlist', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('page_idpage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('plate_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('plate_artist', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('plate_file', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('plate_cover', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('plate_buy_link', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Page', array(
             'local' => 'page_idpage',
             'foreign' => 'idpage'));
    }
}