<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DownloadCatalog', 'doctrine');

/**
 * BaseDownloadCatalog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddownload_catalog
 * @property string $name
 * @property integer $publication
 * @property Doctrine_Collection $BpcmsDownloadCatalogI18n
 * @property Doctrine_Collection $Download
 * 
 * @method integer             getIddownloadCatalog()        Returns the current record's "iddownload_catalog" value
 * @method string              getName()                     Returns the current record's "name" value
 * @method integer             getPublication()              Returns the current record's "publication" value
 * @method Doctrine_Collection getBpcmsDownloadCatalogI18n() Returns the current record's "BpcmsDownloadCatalogI18n" collection
 * @method Doctrine_Collection getDownload()                 Returns the current record's "Download" collection
 * @method DownloadCatalog     setIddownloadCatalog()        Sets the current record's "iddownload_catalog" value
 * @method DownloadCatalog     setName()                     Sets the current record's "name" value
 * @method DownloadCatalog     setPublication()              Sets the current record's "publication" value
 * @method DownloadCatalog     setBpcmsDownloadCatalogI18n() Sets the current record's "BpcmsDownloadCatalogI18n" collection
 * @method DownloadCatalog     setDownload()                 Sets the current record's "Download" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDownloadCatalog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('download_catalog');
        $this->hasColumn('iddownload_catalog', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BpcmsDownloadCatalogI18n', array(
             'local' => 'iddownload_catalog',
             'foreign' => 'download_catalog_iddownload_catalog'));

        $this->hasMany('Download', array(
             'local' => 'iddownload_catalog',
             'foreign' => 'download_catalog_iddownload_catalog'));
    }
}