<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsLangAdmin', 'doctrine');

/**
 * BaseBpcmsLangAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $text_name
 * @property string $text_value
 * 
 * @method string         getTextName()   Returns the current record's "text_name" value
 * @method string         getTextValue()  Returns the current record's "text_value" value
 * @method BpcmsLangAdmin setTextName()   Sets the current record's "text_name" value
 * @method BpcmsLangAdmin setTextValue()  Sets the current record's "text_value" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsLangAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_lang_admin');
        $this->hasColumn('text_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('text_value', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}