<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contact', 'doctrine');

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcontact
 * @property string $name
 * @property string $mail
 * @property string $phone
 * @property string $body
 * 
 * @method integer getIdcontact() Returns the current record's "idcontact" value
 * @method string  getName()      Returns the current record's "name" value
 * @method string  getMail()      Returns the current record's "mail" value
 * @method string  getPhone()     Returns the current record's "phone" value
 * @method string  getBody()      Returns the current record's "body" value
 * @method Contact setIdcontact() Sets the current record's "idcontact" value
 * @method Contact setName()      Sets the current record's "name" value
 * @method Contact setMail()      Sets the current record's "mail" value
 * @method Contact setPhone()     Sets the current record's "phone" value
 * @method Contact setBody()      Sets the current record's "body" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('idcontact', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}