<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsAdminI18n', 'doctrine');

/**
 * BaseBpcmsAdminI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $bpcms_lang_install_signature
 * @property string $lang_text_value
 * @property string $bpcms_lang_admin_text_name
 * 
 * @method string         getBpcmsLangInstallSignature()    Returns the current record's "bpcms_lang_install_signature" value
 * @method string         getLangTextValue()                Returns the current record's "lang_text_value" value
 * @method string         getBpcmsLangAdminTextName()       Returns the current record's "bpcms_lang_admin_text_name" value
 * @method BpcmsAdminI18n setBpcmsLangInstallSignature()    Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsAdminI18n setLangTextValue()                Sets the current record's "lang_text_value" value
 * @method BpcmsAdminI18n setBpcmsLangAdminTextName()       Sets the current record's "bpcms_lang_admin_text_name" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsAdminI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_admin_i18n');
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_text_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('bpcms_lang_admin_text_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}