<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsCartI18n', 'doctrine');

/**
 * BaseBpcmsCartI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cart_idcart
 * @property string $lang_cart_name
 * @property string $lang_title_alt
 * @property string $lang_title_page
 * @property string $lang_cart_name_title
 * @property string $bpcms_lang_install_signature
 * @property string $name_url
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property Cart $Cart
 * 
 * @method integer          getCartIdcart()                   Returns the current record's "cart_idcart" value
 * @method string           getLangCartName()                 Returns the current record's "lang_cart_name" value
 * @method string           getLangTitleAlt()                 Returns the current record's "lang_title_alt" value
 * @method string           getLangTitlePage()                Returns the current record's "lang_title_page" value
 * @method string           getLangCartNameTitle()            Returns the current record's "lang_cart_name_title" value
 * @method string           getBpcmsLangInstallSignature()    Returns the current record's "bpcms_lang_install_signature" value
 * @method string           getNameUrl()                      Returns the current record's "name_url" value
 * @method BpcmsLangInstall getBpcmsLangInstall()             Returns the current record's "BpcmsLangInstall" value
 * @method Cart             getCart()                         Returns the current record's "Cart" value
 * @method BpcmsCartI18n    setCartIdcart()                   Sets the current record's "cart_idcart" value
 * @method BpcmsCartI18n    setLangCartName()                 Sets the current record's "lang_cart_name" value
 * @method BpcmsCartI18n    setLangTitleAlt()                 Sets the current record's "lang_title_alt" value
 * @method BpcmsCartI18n    setLangTitlePage()                Sets the current record's "lang_title_page" value
 * @method BpcmsCartI18n    setLangCartNameTitle()            Sets the current record's "lang_cart_name_title" value
 * @method BpcmsCartI18n    setBpcmsLangInstallSignature()    Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsCartI18n    setNameUrl()                      Sets the current record's "name_url" value
 * @method BpcmsCartI18n    setBpcmsLangInstall()             Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsCartI18n    setCart()                         Sets the current record's "Cart" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsCartI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_cart_i18n');
        $this->hasColumn('cart_idcart', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('lang_cart_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_title_alt', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_title_page', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_cart_name_title', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('name_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('Cart', array(
             'local' => 'cart_idcart',
             'foreign' => 'idcart'));
    }
}