<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsDiplomas', 'doctrine');

/**
 * BaseBpcmsDiplomas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbpcms_diplomas
 * @property string $name
 * @property string $class
 * @property string $title
 * @property string $received
 * @property string $image
 * 
 * @method integer       getIdbpcmsDiplomas()  Returns the current record's "idbpcms_diplomas" value
 * @method string        getName()             Returns the current record's "name" value
 * @method string        getClass()            Returns the current record's "class" value
 * @method string        getTitle()            Returns the current record's "title" value
 * @method string        getReceived()         Returns the current record's "received" value
 * @method string        getImage()            Returns the current record's "image" value
 * @method BpcmsDiplomas setIdbpcmsDiplomas()  Sets the current record's "idbpcms_diplomas" value
 * @method BpcmsDiplomas setName()             Sets the current record's "name" value
 * @method BpcmsDiplomas setClass()            Sets the current record's "class" value
 * @method BpcmsDiplomas setTitle()            Sets the current record's "title" value
 * @method BpcmsDiplomas setReceived()         Sets the current record's "received" value
 * @method BpcmsDiplomas setImage()            Sets the current record's "image" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsDiplomas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_diplomas');
        $this->hasColumn('idbpcms_diplomas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('class', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('received', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}