<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RadioStationScheduleI18n', 'doctrine');

/**
 * BaseRadioStationScheduleI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $radio_station_schedule_idradio_station_schedule
 * @property string $bpcms_lang_install_signature
 * @property string $lang_title
 * @property string $lang_description
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property RadioStationSchedule $RadioStationSchedule
 * 
 * @method integer                  getRadioStationScheduleIdradioStationSchedule()      Returns the current record's "radio_station_schedule_idradio_station_schedule" value
 * @method string                   getBpcmsLangInstallSignature()                       Returns the current record's "bpcms_lang_install_signature" value
 * @method string                   getLangTitle()                                       Returns the current record's "lang_title" value
 * @method string                   getLangDescription()                                 Returns the current record's "lang_description" value
 * @method BpcmsLangInstall         getBpcmsLangInstall()                                Returns the current record's "BpcmsLangInstall" value
 * @method RadioStationSchedule     getRadioStationSchedule()                            Returns the current record's "RadioStationSchedule" value
 * @method RadioStationScheduleI18n setRadioStationScheduleIdradioStationSchedule()      Sets the current record's "radio_station_schedule_idradio_station_schedule" value
 * @method RadioStationScheduleI18n setBpcmsLangInstallSignature()                       Sets the current record's "bpcms_lang_install_signature" value
 * @method RadioStationScheduleI18n setLangTitle()                                       Sets the current record's "lang_title" value
 * @method RadioStationScheduleI18n setLangDescription()                                 Sets the current record's "lang_description" value
 * @method RadioStationScheduleI18n setBpcmsLangInstall()                                Sets the current record's "BpcmsLangInstall" value
 * @method RadioStationScheduleI18n setRadioStationSchedule()                            Sets the current record's "RadioStationSchedule" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadioStationScheduleI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radio_station_schedule_i18n');
        $this->hasColumn('radio_station_schedule_idradio_station_schedule', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lang_description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('RadioStationSchedule', array(
             'local' => 'radio_station_schedule_idradio_station_schedule',
             'foreign' => 'idradio_station_schedule'));
    }
}