<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsGalleryCatalogI18n', 'doctrine');

/**
 * BaseBpcmsGalleryCatalogI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gallery_catalog_idgallery_catalog
 * @property string $bpcms_lang_install_signature
 * @property string $lang_catalog_name
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property GalleryCatalog $GalleryCatalog
 * 
 * @method integer                 getGalleryCatalogIdgalleryCatalog()    Returns the current record's "gallery_catalog_idgallery_catalog" value
 * @method string                  getBpcmsLangInstallSignature()         Returns the current record's "bpcms_lang_install_signature" value
 * @method string                  getLangCatalogName()                   Returns the current record's "lang_catalog_name" value
 * @method BpcmsLangInstall        getBpcmsLangInstall()                  Returns the current record's "BpcmsLangInstall" value
 * @method GalleryCatalog          getGalleryCatalog()                    Returns the current record's "GalleryCatalog" value
 * @method BpcmsGalleryCatalogI18n setGalleryCatalogIdgalleryCatalog()    Sets the current record's "gallery_catalog_idgallery_catalog" value
 * @method BpcmsGalleryCatalogI18n setBpcmsLangInstallSignature()         Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsGalleryCatalogI18n setLangCatalogName()                   Sets the current record's "lang_catalog_name" value
 * @method BpcmsGalleryCatalogI18n setBpcmsLangInstall()                  Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsGalleryCatalogI18n setGalleryCatalog()                    Sets the current record's "GalleryCatalog" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsGalleryCatalogI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_gallery_catalog_i18n');
        $this->hasColumn('gallery_catalog_idgallery_catalog', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_catalog_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('GalleryCatalog', array(
             'local' => 'gallery_catalog_idgallery_catalog',
             'foreign' => 'idgallery_catalog'));
    }
}