<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsTextI18n', 'doctrine');

/**
 * BaseBpcmsTextI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $bpcms_lang_install_signature
 * @property string $lang_text_value
 * @property string $bpcms_lang_text_text_name
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property BpcmsLangText $BpcmsLangText
 * 
 * @method string           getBpcmsLangInstallSignature()    Returns the current record's "bpcms_lang_install_signature" value
 * @method string           getLangTextValue()                Returns the current record's "lang_text_value" value
 * @method string           getBpcmsLangTextTextName()        Returns the current record's "bpcms_lang_text_text_name" value
 * @method BpcmsLangInstall getBpcmsLangInstall()             Returns the current record's "BpcmsLangInstall" value
 * @method BpcmsLangText    getBpcmsLangText()                Returns the current record's "BpcmsLangText" value
 * @method BpcmsTextI18n    setBpcmsLangInstallSignature()    Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsTextI18n    setLangTextValue()                Sets the current record's "lang_text_value" value
 * @method BpcmsTextI18n    setBpcmsLangTextTextName()        Sets the current record's "bpcms_lang_text_text_name" value
 * @method BpcmsTextI18n    setBpcmsLangInstall()             Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsTextI18n    setBpcmsLangText()                Sets the current record's "BpcmsLangText" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsTextI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_text_i18n');
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_text_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('bpcms_lang_text_text_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('BpcmsLangText', array(
             'local' => 'bpcms_lang_text_text_name',
             'foreign' => 'text_name'));
    }
}