<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Configuration', 'doctrine');

/**
 * BaseConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idconfiguration
 * @property string $config_name
 * @property string $config_option
 * @property string $config_value
 * @property integer $config_on
 * 
 * @method integer       getIdconfiguration() Returns the current record's "idconfiguration" value
 * @method string        getConfigName()      Returns the current record's "config_name" value
 * @method string        getConfigOption()    Returns the current record's "config_option" value
 * @method string        getConfigValue()     Returns the current record's "config_value" value
 * @method integer       getConfigOn()        Returns the current record's "config_on" value
 * @method Configuration setIdconfiguration() Sets the current record's "idconfiguration" value
 * @method Configuration setConfigName()      Sets the current record's "config_name" value
 * @method Configuration setConfigOption()    Sets the current record's "config_option" value
 * @method Configuration setConfigValue()     Sets the current record's "config_value" value
 * @method Configuration setConfigOn()        Sets the current record's "config_on" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configuration');
        $this->hasColumn('idconfiguration', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('config_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('config_option', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('config_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('config_on', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}