<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RadioStationSchedule', 'doctrine');

/**
 * BaseRadioStationSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idradio_station_schedule
 * @property string $title
 * @property string $description
 * @property string $broadcast_hour
 * @property string $broadcast_day_a_week
 * @property integer $position_row
 * @property integer $radio_station_idradio_station
 * @property integer $publication
 * @property RadioStation $RadioStation
 * @property Doctrine_Collection $RadioStationScheduleI18n
 * 
 * @method integer              getIdradioStationSchedule()        Returns the current record's "idradio_station_schedule" value
 * @method string               getTitle()                         Returns the current record's "title" value
 * @method string               getDescription()                   Returns the current record's "description" value
 * @method string               getBroadcastHour()                 Returns the current record's "broadcast_hour" value
 * @method string               getBroadcastDayAWeek()             Returns the current record's "broadcast_day_a_week" value
 * @method integer              getPositionRow()                   Returns the current record's "position_row" value
 * @method integer              getRadioStationIdradioStation()    Returns the current record's "radio_station_idradio_station" value
 * @method integer              getPublication()                   Returns the current record's "publication" value
 * @method RadioStation         getRadioStation()                  Returns the current record's "RadioStation" value
 * @method Doctrine_Collection  getRadioStationScheduleI18n()      Returns the current record's "RadioStationScheduleI18n" collection
 * @method RadioStationSchedule setIdradioStationSchedule()        Sets the current record's "idradio_station_schedule" value
 * @method RadioStationSchedule setTitle()                         Sets the current record's "title" value
 * @method RadioStationSchedule setDescription()                   Sets the current record's "description" value
 * @method RadioStationSchedule setBroadcastHour()                 Sets the current record's "broadcast_hour" value
 * @method RadioStationSchedule setBroadcastDayAWeek()             Sets the current record's "broadcast_day_a_week" value
 * @method RadioStationSchedule setPositionRow()                   Sets the current record's "position_row" value
 * @method RadioStationSchedule setRadioStationIdradioStation()    Sets the current record's "radio_station_idradio_station" value
 * @method RadioStationSchedule setPublication()                   Sets the current record's "publication" value
 * @method RadioStationSchedule setRadioStation()                  Sets the current record's "RadioStation" value
 * @method RadioStationSchedule setRadioStationScheduleI18n()      Sets the current record's "RadioStationScheduleI18n" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadioStationSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radio_station_schedule');
        $this->hasColumn('idradio_station_schedule', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('broadcast_hour', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('broadcast_day_a_week', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('position_row', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('radio_station_idradio_station', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RadioStation', array(
             'local' => 'radio_station_idradio_station',
             'foreign' => 'idradio_station'));

        $this->hasMany('RadioStationScheduleI18n', array(
             'local' => 'idradio_station_schedule',
             'foreign' => 'radio_station_schedule_idradio_station_schedule'));
    }
}