<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsDownloadI18n', 'doctrine');

/**
 * BaseBpcmsDownloadI18n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $download_iddownload
 * @property string $bpcms_lang_install_signature
 * @property string $lang_title
 * @property BpcmsLangInstall $BpcmsLangInstall
 * @property Download $Download
 * 
 * @method integer           getDownloadIddownload()           Returns the current record's "download_iddownload" value
 * @method string            getBpcmsLangInstallSignature()    Returns the current record's "bpcms_lang_install_signature" value
 * @method string            getLangTitle()                    Returns the current record's "lang_title" value
 * @method BpcmsLangInstall  getBpcmsLangInstall()             Returns the current record's "BpcmsLangInstall" value
 * @method Download          getDownload()                     Returns the current record's "Download" value
 * @method BpcmsDownloadI18n setDownloadIddownload()           Sets the current record's "download_iddownload" value
 * @method BpcmsDownloadI18n setBpcmsLangInstallSignature()    Sets the current record's "bpcms_lang_install_signature" value
 * @method BpcmsDownloadI18n setLangTitle()                    Sets the current record's "lang_title" value
 * @method BpcmsDownloadI18n setBpcmsLangInstall()             Sets the current record's "BpcmsLangInstall" value
 * @method BpcmsDownloadI18n setDownload()                     Sets the current record's "Download" value
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsDownloadI18n extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_download_i18n');
        $this->hasColumn('download_iddownload', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_lang_install_signature', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('lang_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsLangInstall', array(
             'local' => 'bpcms_lang_install_signature',
             'foreign' => 'signature'));

        $this->hasOne('Download', array(
             'local' => 'download_iddownload',
             'foreign' => 'iddownload'));
    }
}