<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Broadcasts', 'doctrine');

/**
 * BaseBroadcasts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbroadcasts
 * @property string $name_pl
 * @property string $description_pl
 * @property string $avatar
 * @property integer $publication
 * @property string $description_de
 * @property string $name_de
 * @property string $name_cz
 * @property string $description_cz
 * @property Doctrine_Collection $Schedule
 * 
 * @method integer             getIdbroadcasts()   Returns the current record's "idbroadcasts" value
 * @method string              getNamePl()         Returns the current record's "name_pl" value
 * @method string              getDescriptionPl()  Returns the current record's "description_pl" value
 * @method string              getAvatar()         Returns the current record's "avatar" value
 * @method integer             getPublication()    Returns the current record's "publication" value
 * @method string              getDescriptionDe()  Returns the current record's "description_de" value
 * @method string              getNameDe()         Returns the current record's "name_de" value
 * @method string              getNameCz()         Returns the current record's "name_cz" value
 * @method string              getDescriptionCz()  Returns the current record's "description_cz" value
 * @method Doctrine_Collection getSchedule()       Returns the current record's "Schedule" collection
 * @method Broadcasts          setIdbroadcasts()   Sets the current record's "idbroadcasts" value
 * @method Broadcasts          setNamePl()         Sets the current record's "name_pl" value
 * @method Broadcasts          setDescriptionPl()  Sets the current record's "description_pl" value
 * @method Broadcasts          setAvatar()         Sets the current record's "avatar" value
 * @method Broadcasts          setPublication()    Sets the current record's "publication" value
 * @method Broadcasts          setDescriptionDe()  Sets the current record's "description_de" value
 * @method Broadcasts          setNameDe()         Sets the current record's "name_de" value
 * @method Broadcasts          setNameCz()         Sets the current record's "name_cz" value
 * @method Broadcasts          setDescriptionCz()  Sets the current record's "description_cz" value
 * @method Broadcasts          setSchedule()       Sets the current record's "Schedule" collection
 * 
 * @package    mittendrin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBroadcasts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('broadcasts');
        $this->hasColumn('idbroadcasts', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name_pl', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description_pl', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('avatar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description_de', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('name_de', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('name_cz', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('description_cz', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Schedule', array(
             'local' => 'idbroadcasts',
             'foreign' => 'broadcasts_idbroadcasts'));
    }
}