<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsAlbumMonth', 'doctrine');

/**
 * BaseBpcmsAlbumMonth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbpcms_album_month
 * @property string $title
 * @property string $description
 * @property string $link
 * @property integer $publication
 * @property string $avatar
 * @property Doctrine_Collection $BpcmsAlbumMonthI18n
 * 
 * @method integer             getIdbpcmsAlbumMonth()   Returns the current record's "idbpcms_album_month" value
 * @method string              getTitle()               Returns the current record's "title" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method string              getLink()                Returns the current record's "link" value
 * @method integer             getPublication()         Returns the current record's "publication" value
 * @method string              getAvatar()              Returns the current record's "avatar" value
 * @method Doctrine_Collection getBpcmsAlbumMonthI18n() Returns the current record's "BpcmsAlbumMonthI18n" collection
 * @method BpcmsAlbumMonth     setIdbpcmsAlbumMonth()   Sets the current record's "idbpcms_album_month" value
 * @method BpcmsAlbumMonth     setTitle()               Sets the current record's "title" value
 * @method BpcmsAlbumMonth     setDescription()         Sets the current record's "description" value
 * @method BpcmsAlbumMonth     setLink()                Sets the current record's "link" value
 * @method BpcmsAlbumMonth     setPublication()         Sets the current record's "publication" value
 * @method BpcmsAlbumMonth     setAvatar()              Sets the current record's "avatar" value
 * @method BpcmsAlbumMonth     setBpcmsAlbumMonthI18n() Sets the current record's "BpcmsAlbumMonthI18n" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsAlbumMonth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_album_month');
        $this->hasColumn('idbpcms_album_month', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('avatar', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BpcmsAlbumMonthI18n', array(
             'local' => 'idbpcms_album_month',
             'foreign' => 'album_month_idalbum_month'));
    }
}