<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BpcmsYtMovies', 'doctrine');

/**
 * BaseBpcmsYtMovies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbpcms_yt_movies
 * @property string $title
 * @property string $description
 * @property string $avatar
 * @property string $created_at
 * @property integer $publication
 * @property integer $bpcms_yt_catalog_idbpcms_yt_catalog
 * @property integer $recommended
 * @property string $youtube_iframe
 * @property BpcmsYtCatalog $BpcmsYtCatalog
 * @property Doctrine_Collection $BpcmsYtMoviesI18n
 * 
 * @method integer             getIdbpcmsYtMovies()                     Returns the current record's "idbpcms_yt_movies" value
 * @method string              getTitle()                               Returns the current record's "title" value
 * @method string              getDescription()                         Returns the current record's "description" value
 * @method string              getAvatar()                              Returns the current record's "avatar" value
 * @method string              getCreatedAt()                           Returns the current record's "created_at" value
 * @method integer             getPublication()                         Returns the current record's "publication" value
 * @method integer             getBpcmsYtCatalogIdbpcmsYtCatalog()      Returns the current record's "bpcms_yt_catalog_idbpcms_yt_catalog" value
 * @method integer             getRecommended()                         Returns the current record's "recommended" value
 * @method string              getYoutubeIframe()                       Returns the current record's "youtube_iframe" value
 * @method BpcmsYtCatalog      getBpcmsYtCatalog()                      Returns the current record's "BpcmsYtCatalog" value
 * @method Doctrine_Collection getBpcmsYtMoviesI18n()                   Returns the current record's "BpcmsYtMoviesI18n" collection
 * @method BpcmsYtMovies       setIdbpcmsYtMovies()                     Sets the current record's "idbpcms_yt_movies" value
 * @method BpcmsYtMovies       setTitle()                               Sets the current record's "title" value
 * @method BpcmsYtMovies       setDescription()                         Sets the current record's "description" value
 * @method BpcmsYtMovies       setAvatar()                              Sets the current record's "avatar" value
 * @method BpcmsYtMovies       setCreatedAt()                           Sets the current record's "created_at" value
 * @method BpcmsYtMovies       setPublication()                         Sets the current record's "publication" value
 * @method BpcmsYtMovies       setBpcmsYtCatalogIdbpcmsYtCatalog()      Sets the current record's "bpcms_yt_catalog_idbpcms_yt_catalog" value
 * @method BpcmsYtMovies       setRecommended()                         Sets the current record's "recommended" value
 * @method BpcmsYtMovies       setYoutubeIframe()                       Sets the current record's "youtube_iframe" value
 * @method BpcmsYtMovies       setBpcmsYtCatalog()                      Sets the current record's "BpcmsYtCatalog" value
 * @method BpcmsYtMovies       setBpcmsYtMoviesI18n()                   Sets the current record's "BpcmsYtMoviesI18n" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBpcmsYtMovies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bpcms_yt_movies');
        $this->hasColumn('idbpcms_yt_movies', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('avatar', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('created_at', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bpcms_yt_catalog_idbpcms_yt_catalog', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('recommended', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('youtube_iframe', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BpcmsYtCatalog', array(
             'local' => 'bpcms_yt_catalog_idbpcms_yt_catalog',
             'foreign' => 'idbpcms_yt_catalog'));

        $this->hasMany('BpcmsYtMoviesI18n', array(
             'local' => 'idbpcms_yt_movies',
             'foreign' => 'bpcms_yt_movies_idbpcms_yt_movies'));
    }
}