<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Download', 'doctrine');

/**
 * BaseDownload
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddownload
 * @property string $file_name
 * @property string $title
 * @property integer $publication
 * @property integer $download_catalog_iddownload_catalog
 * @property string $url_to_file
 * @property DownloadCatalog $DownloadCatalog
 * @property Doctrine_Collection $BpcmsDownloadI18n
 * 
 * @method integer             getIddownload()                          Returns the current record's "iddownload" value
 * @method string              getFileName()                            Returns the current record's "file_name" value
 * @method string              getTitle()                               Returns the current record's "title" value
 * @method integer             getPublication()                         Returns the current record's "publication" value
 * @method integer             getDownloadCatalogIddownloadCatalog()    Returns the current record's "download_catalog_iddownload_catalog" value
 * @method string              getUrlToFile()                           Returns the current record's "url_to_file" value
 * @method DownloadCatalog     getDownloadCatalog()                     Returns the current record's "DownloadCatalog" value
 * @method Doctrine_Collection getBpcmsDownloadI18n()                   Returns the current record's "BpcmsDownloadI18n" collection
 * @method Download            setIddownload()                          Sets the current record's "iddownload" value
 * @method Download            setFileName()                            Sets the current record's "file_name" value
 * @method Download            setTitle()                               Sets the current record's "title" value
 * @method Download            setPublication()                         Sets the current record's "publication" value
 * @method Download            setDownloadCatalogIddownloadCatalog()    Sets the current record's "download_catalog_iddownload_catalog" value
 * @method Download            setUrlToFile()                           Sets the current record's "url_to_file" value
 * @method Download            setDownloadCatalog()                     Sets the current record's "DownloadCatalog" value
 * @method Download            setBpcmsDownloadI18n()                   Sets the current record's "BpcmsDownloadI18n" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDownload extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('download');
        $this->hasColumn('iddownload', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('file_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('download_catalog_iddownload_catalog', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('url_to_file', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DownloadCatalog', array(
             'local' => 'download_catalog_iddownload_catalog',
             'foreign' => 'iddownload_catalog'));

        $this->hasMany('BpcmsDownloadI18n', array(
             'local' => 'iddownload',
             'foreign' => 'download_iddownload'));
    }
}