<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cart', 'doctrine');

/**
 * BaseCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcart
 * @property string $cart_name
 * @property string $title_alt
 * @property string $title_page
 * @property integer $no_page
 * @property integer $publication
 * @property string $position
 * @property integer $position_order
 * @property integer $link_active
 * @property string $cart_name_title
 * @property string $redirect_to_url
 * @property string $redirect_to_url_blank_open
 * @property string $position_row
 * @property string $name_url
 * @property Doctrine_Collection $BpcmsCartI18n
 * @property Doctrine_Collection $Page
 * 
 * @method integer             getIdcart()                     Returns the current record's "idcart" value
 * @method string              getCartName()                   Returns the current record's "cart_name" value
 * @method string              getTitleAlt()                   Returns the current record's "title_alt" value
 * @method string              getTitlePage()                  Returns the current record's "title_page" value
 * @method integer             getNoPage()                     Returns the current record's "no_page" value
 * @method integer             getPublication()                Returns the current record's "publication" value
 * @method string              getPosition()                   Returns the current record's "position" value
 * @method integer             getPositionOrder()              Returns the current record's "position_order" value
 * @method integer             getLinkActive()                 Returns the current record's "link_active" value
 * @method string              getCartNameTitle()              Returns the current record's "cart_name_title" value
 * @method string              getRedirectToUrl()              Returns the current record's "redirect_to_url" value
 * @method string              getRedirectToUrlBlankOpen()     Returns the current record's "redirect_to_url_blank_open" value
 * @method string              getPositionRow()                Returns the current record's "position_row" value
 * @method string              getNameUrl()                    Returns the current record's "name_url" value
 * @method Doctrine_Collection getBpcmsCartI18n()              Returns the current record's "BpcmsCartI18n" collection
 * @method Doctrine_Collection getPage()                       Returns the current record's "Page" collection
 * @method Cart                setIdcart()                     Sets the current record's "idcart" value
 * @method Cart                setCartName()                   Sets the current record's "cart_name" value
 * @method Cart                setTitleAlt()                   Sets the current record's "title_alt" value
 * @method Cart                setTitlePage()                  Sets the current record's "title_page" value
 * @method Cart                setNoPage()                     Sets the current record's "no_page" value
 * @method Cart                setPublication()                Sets the current record's "publication" value
 * @method Cart                setPosition()                   Sets the current record's "position" value
 * @method Cart                setPositionOrder()              Sets the current record's "position_order" value
 * @method Cart                setLinkActive()                 Sets the current record's "link_active" value
 * @method Cart                setCartNameTitle()              Sets the current record's "cart_name_title" value
 * @method Cart                setRedirectToUrl()              Sets the current record's "redirect_to_url" value
 * @method Cart                setRedirectToUrlBlankOpen()     Sets the current record's "redirect_to_url_blank_open" value
 * @method Cart                setPositionRow()                Sets the current record's "position_row" value
 * @method Cart                setNameUrl()                    Sets the current record's "name_url" value
 * @method Cart                setBpcmsCartI18n()              Sets the current record's "BpcmsCartI18n" collection
 * @method Cart                setPage()                       Sets the current record's "Page" collection
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cart');
        $this->hasColumn('idcart', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cart_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('title_alt', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('title_page', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('no_page', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('publication', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('position', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('position_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('link_active', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cart_name_title', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('redirect_to_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('redirect_to_url_blank_open', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('position_row', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('name_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BpcmsCartI18n', array(
             'local' => 'idcart',
             'foreign' => 'cart_idcart'));

        $this->hasMany('Page', array(
             'local' => 'idcart',
             'foreign' => 'cart_idcart'));
    }
}