<?php

/**
 * BoxesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoxesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoxesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Boxes');
    }
}