<?php

/**
 * Boxes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Boxes extends BaseBoxes
{
    public function getBoxImage() {
        return image_tag('boxes/'.parent::getImage(), array('width-max' => 296));
    }
    
    public function getBoxImageWithLink() {
        if(parent::getUrlForPage() != '') {
            if(parent::getTarget() == 1) {
                return link_to(self::getBoxImage(), parent::getUrlForPage(), array('target' => '_blank'));                
            } else {
                return link_to(self::getBoxImage(), parent::getUrlForPage());                
            }
        } else {
            return self::getBoxImage();
        }
    }
}
