<?php

/**
 * BpcmsLangTextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsLangTextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsLangTextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsLangText');
    }
}