<?php

/**
 * BpcmsAdminI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsAdminI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsAdminI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsAdminI18n');
    }
}