<?php

/**
 * BpcmsDiplomasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsDiplomasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsDiplomasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsDiplomas');
    }
}