<?php

/**
 * BpcmsGalleryI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsGalleryI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsGalleryI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsGalleryI18n');
    }
}