<?php

/**
 * BpcmsAlbumMonthI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsAlbumMonthI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsAlbumMonthI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsAlbumMonthI18n');
    }
}