<?php

/**
 * BpcmsPlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsPlaylistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsPlaylistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsPlaylist');
    }
}