<?php

/**
 * BpcmsDownloadI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsDownloadI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsDownloadI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsDownloadI18n');
    }
}