<?php

/**
 * BpcmsYtCatalogI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsYtCatalogI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsYtCatalogI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsYtCatalogI18n');
    }
}