<?php

/**
 * BpcmsLangInstallTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsLangInstallTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsLangInstallTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('BpcmsLangInstall');
    }


}
