<?php

/**
 * BpcmsYtMoviesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsYtMoviesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsYtMoviesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsYtMovies');
    }
}