<?php

/**
 * BpcmsGalleryCatalogI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsGalleryCatalogI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsGalleryCatalogI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsGalleryCatalogI18n');
    }
}