<?php

/**
 * BpcmsGalleryCategoryI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsGalleryCategoryI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsGalleryCategoryI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsGalleryCategoryI18n');
    }
}