<?php

/**
 * BpcmsAlbumMonth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BpcmsAlbumMonth extends BaseBpcmsAlbumMonth
{
    public function getStatus() {
        $status = new Status(parent::getPublication());

        return $status->getPublication();
    }

    public function getLangTitle() {
        $bpcms_album_month_i18n = Doctrine_Core::getTable('BpcmsAlbumMonthI18n')->createQuery('a')
            ->where('a.album_month_idalbum_month = ?', parent::getIdbpcmsAlbumMonth())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($bpcms_album_month_i18n) {
            return $bpcms_album_month_i18n->getLangTitle() ? $bpcms_album_month_i18n->getLangTitle() : parent::getTitle();
        } else {
            return parent::getTitle();
        }
    }

    public function getLangDescription() {
        $bpcms_album_month_i18n = Doctrine_Core::getTable('BpcmsAlbumMonthI18n')->createQuery('a')
            ->where('a.album_month_idalbum_month = ?', parent::getIdbpcmsAlbumMonth())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($bpcms_album_month_i18n) {
            return $bpcms_album_month_i18n->getLangDescription() ? $bpcms_album_month_i18n->getLangDescription() : parent::getDescription();
        } else {
            return parent::getDescription();
        }
    }

}
