<?php

/**
 * BpcmsDownloadCatalogI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsDownloadCatalogI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsDownloadCatalogI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsDownloadCatalogI18n');
    }
}