<?php

/**
 * BpcmsSlideshowI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsSlideshowI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsSlideshowI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsSlideshowI18n');
    }
}