<?php

/**
 * BpcmsYtMoviesI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsYtMoviesI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsYtMoviesI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsYtMoviesI18n');
    }
}