<?php

/**
 * BpcmsLangInstall
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BpcmsLangInstall extends BaseBpcmsLangInstall {

    public function getStatus() {
        $status = new Status(parent::getPublication());

        return $status->getPublication();
    }

    public function getDefaultLang() {
        $status = new Status(parent::getActive());

        return $status->getActive();
    }

    public function getLinkWithStatus($table = null, $column = null, $content_id = null, $content_value = null) {
        $lang_install = Doctrine_Core::getTable($table)->createQuery('a')
                ->where('a.' . $column . ' = ?', $value)
                ->andWhere('a.bpcms_lang_install_signature = ?', parent::getSignature())
                ->andWhere('a.' . $content_id . ' = ?', $content_value)
                ->fetchOne();

        if ($lang_install) {
            return 'edycja';
        } else {
            //bpcmsLangInstall/new?signature='.parent::getSignature().'&col='.$column
            return link_to(parent::getName() . ' dodaj tłumaczenie w tym języku', '/#myModal', array('data-toggle' => 'modal'));
        }
    }

    public function getObjectType($table = null, $column = null, $value = null) {
        $lang_install = Doctrine_Core::getTable($table)->createQuery('a')
                ->where('a.' . $column . ' = ?', $value)
                ->andWhere('a.bpcms_lang_install_signature = ?', parent::getSignature())
                ->fetchOne();

        switch ($table) {
            case "BpcmsCartI18n":
                if ($lang_install) {
                    return new BpcmsCartI18nForm($lang_install);
                } else {
                    return new BpcmsCartI18nForm();
                }
                break;
            case "BpcmsPageI18n":
                if ($lang_install) {
                    return new BpcmsPageI18nForm($lang_install);
                } else {
                    return new BpcmsPageI18nForm();
                }
                break;
            case "BpcmsPostI18n":
                if ($lang_install) {
                    return new BpcmsPostI18nForm($lang_install);
                } else {
                    return new BpcmsPostI18nForm();
                }
                break;
            case "BpcmsDownloadI18n":
                if ($lang_install) {
                    return new BpcmsDownloadI18nForm($lang_install);
                } else {
                    return new BpcmsDownloadI18nForm();
                }
                break;
            case "BpcmsTextI18n":
                if ($lang_install) {
                    return new BpcmsTextI18nForm($lang_install);
                } else {
                    return new BpcmsTextI18nForm();
                }
                break;
            case "BpcmsGalleryCatalogI18n":
                if ($lang_install) {
                    return new BpcmsGalleryCatalogI18nForm($lang_install);
                } else {
                    return new BpcmsGalleryCatalogI18nForm();
                }
                break;
            case "BpcmsGalleryCategoryI18n":
                if ($lang_install) {
                    return new BpcmsGalleryCategoryI18nForm($lang_install);
                } else {
                    return new BpcmsGalleryCategoryI18nForm();
                }
                break;
            case "BpcmsGalleryI18n":
                if ($lang_install) {
                    return new BpcmsGalleryI18nForm($lang_install);
                } else {
                    return new BpcmsGalleryI18nForm();
                }
                break;
            case "BpcmsAlbumMonthI18n":
                if ($lang_install) {
                    return new BpcmsAlbumMonthI18nForm($lang_install);
                } else {
                    return new BpcmsAlbumMonthI18nForm();
                }
                break;
            case "RadioStationI18n":
                if ($lang_install) {
                    return new RadioStationI18nForm($lang_install);
                } else {
                    return new RadioStationI18nForm();
                }
                break;
            case "RadioStationScheduleI18n":
                if ($lang_install) {
                    return new RadioStationScheduleI18nForm($lang_install);
                } else {
                    return new RadioStationScheduleI18nForm();
                }
                break;
            case "BpcmsPostCatalogI18n":
                if ($lang_install) {
                    return new BpcmsPostCatalogI18nForm($lang_install);
                } else {
                    return new BpcmsPostCatalogI18nForm();
                }
                break;
            case "BpcmsYtCatalogI18n":
                if ($lang_install) {
                    return new BpcmsYtCatalogI18nForm($lang_install);
                } else {
                    return new BpcmsYtCatalogI18nForm();
                }
                break;
            case "BpcmsYtMoviesI18n":
                if ($lang_install) {
                    return new BpcmsYtMoviesI18nForm($lang_install);
                } else {
                    return new BpcmsYtMoviesI18nForm();
                }
                break;
            case "BpcmsSlideshowI18n":
                if ($lang_install) {
                    return new BpcmsSlideshowI18nForm($lang_install);
                } else {
                    return new BpcmsSlideshowI18nForm();
                }
                break;
        }

    }

}
