<?php

/**
 * BpcmsYtMovies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BpcmsYtMovies extends BaseBpcmsYtMovies {

    public function getStatus() {
        $status = new Status(parent::getPublication());

        return $status->getPublication();
    }

    public function getStatusRecommended() {
        $status = new Status(parent::getPublication());

        return $status->getPublication();
    }

    public function getLangTitle()
    {
        $bpcms_yt_movies_i18n = Doctrine_Core::getTable('BpcmsYtMoviesI18n')->createQuery('a')
            ->where('a.bpcms_yt_movies_idbpcms_yt_movies = ?', parent::getIdbpcmsYtMovies())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($bpcms_yt_movies_i18n) {
            return $bpcms_yt_movies_i18n->getLangTitle() ? $bpcms_yt_movies_i18n->getLangTitle() : parent::getTitle();
        } else {
            return parent::getTitle();
        }
    }

    public function getLangDescription()
    {
        $bpcms_yt_movies_i18n = Doctrine_Core::getTable('BpcmsYtMoviesI18n')->createQuery('a')
            ->where('a.bpcms_yt_movies_idbpcms_yt_movies = ?', parent::getIdbpcmsYtMovies())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($bpcms_yt_movies_i18n) {
            return $bpcms_yt_movies_i18n->getLangDescription() ? $bpcms_yt_movies_i18n->getLangDescription() : parent::getDescription();
        } else {
            return parent::getDescription();
        }
    }

    public function getLangDescriptionHeader() {
        $content = strip_tags(self::getLangDescription(), 'p');

        $ex = explode("</p>", $content);

        return $ex['0'] . '</p>';
    }

    public function getLangDescriptionLong() {
        $content = self::getLangDescription();

        $ex = explode("</p>", $content);

        for ($line = 1; $line < count($ex) + 1; $line++) {
            $content_body .= $ex[$line] . '</p>';
        }

        return $content_body;
    }

    public function getLinkToShowUrl() {
        $request = sfContext::getInstance()->getRequest();

//        sfContext::getInstance()->getConfiguration()->loadHelpers(array('Url'));

        $string = 'yt_movies_show' . ($request->getParameter('culture') ? '_lang?culture=' . $request->getParameter('culture') . '&' : '?') . 'idbpcms_yt_movies=' . parent::getIdbpcmsYtMovies() . '&name=' . Configuration::getStringAndReplace(parent::getLangTitle());

        return url_for('@' . $string);
    }

    public function getLinkToShowCatalogUrl() {
        $request = sfContext::getInstance()->getRequest();

        $string = 'yt_movies_show_catalog' . ($request->getParameter('culture') ? '_lang?culture=' . $request->getParameter('culture') . '&' : '?') . 'idbpcms_yt_catalog=' . parent::getBpcmsYtCatalogIdbpcmsYtCatalog() . '&name=' . Configuration::getStringAndReplace(parent::getBpcmsYtCatalog()->getName());

        return url_for('@' . $string);
    }

    public function getImage() {

        $image_url = 'https://'.$_SERVER['HTTP_HOST'].'/images/yt_movies/'.parent::getAvatar();

        if(@getimagesize($image_url)) {
            return $image_url;
        } else {
            return '/images/no-photo.jpg';
        }
    }

}
