<?php

/**
 * BpcmsAlbumMonthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsAlbumMonthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsAlbumMonthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsAlbumMonth');
    }
}