<?php

/**
 * BpcmsCartI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsCartI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsCartI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsCartI18n');
    }
}