<?php

/**
 * BpcmsPageI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BpcmsPageI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BpcmsPageI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BpcmsPageI18n');
    }
}