<?php

/**
 * Broadcasts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mittendrin
 * @subpackage model
 * @author     Damian Kania@eddi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Broadcasts extends BaseBroadcasts
{
	public static function getBroadcastsNameWithId($id = null)
	{
		$catalog = Doctrine::getTable('Broadcasts')->find(array(12));
		
		return $catalog->getNamePl();
	}
	
	public function __toString()
	{
		return $this->getNamePl();
	}
	
	public function getName() {
            switch (sfContext::getInstance()->getUser()->getCulture()) {
                case 'pl':
                    return parent::getNamePl();
                    break;
                case 'de':
                    return parent::getNameDe() ? parent::getNameDe() : parent::getNamePl();
                    break;
                case 'cz':
                    return parent::getNameCz() ? parent::getNameCz() : parent::getNamePl();
                    break;
            }
	}
        
	public function getDescription() {
            switch (sfContext::getInstance()->getUser()->getCulture()) {
                case 'pl':
                    return parent::getDescriptionPl();
                    break;
                case 'de':
                    return parent::getDescriptionDe() ? parent::getDescriptionDe() : parent::getDescriptionPl();
                    break;
                case 'cz':
                    return parent::getDescriptionCz() ? parent::getDescriptionCz() : parent::getDescriptionPl();
                    break;
            }
	}
}