<?php

/**
 * Cart
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cart extends BaseCart
{

    public function __toString()
    {
        return parent::getCartName();
    }

    public function getLangCartName()
    {
        $bpcms_page_i18n = Doctrine_Core::getTable('BpcmsCartI18n')->createQuery('a')
            ->where('a.cart_idcart = ?', parent::getIdcart())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($bpcms_page_i18n) {
            return $bpcms_page_i18n->getLangCartName();
        } else {
            return parent::getCartName();
        }
    }

    public function getLangCartNameTitle()
    {
        $bpcms_page_i18n = Doctrine_Core::getTable('BpcmsCartI18n')->createQuery('a')
            ->where('a.cart_idcart = ?', parent::getIdcart())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($bpcms_page_i18n) {
            return $bpcms_page_i18n->getLangCartNameTitle();
        } else {
            return parent::getCartNameTitle();
        }
    }

    public function getNameForLink()
    {
        return Configuration::getStringAndReplace(self::getLangCartName());
    }

    public function getPagelist()
    {
        if (sfConfig::get('sf_app') == 'page') {
            $pages = Doctrine_Core::getTable('Page')
                ->createQuery('a')
                ->where('a.cart_idcart = ? AND a.publication = ?', array(parent::getIdcart(), 1))
                ->orderBy('a.position_row ASC')
                ->execute();
        } else {
                $pages = Doctrine_Core::getTable('Page')
                    ->createQuery('a')
                    ->where('a.cart_idcart = ?', parent::getIdcart())
                    ->orderBy('a.position_row ASC')
                    ->execute();
        }

        return $pages;

    }

    public function getPublicationLink()
    {
        if (parent::getPublication() == 1) {
            return link_to('ukryj', 'cart/publication?idcart=' . parent::getIdcart(), array('class' => 'btn btn-warning btn-mini'));
        } else {
            return link_to('pokaż', 'cart/publication?idcart=' . parent::getIdcart(), array('class' => 'btn btn-warning btn-mini'));
        }
    }

    public function getNoPageLink()
    {
        if (parent::getNoPage() == 1) {
            return link_to('włącz', 'cart/nopage?idcart=' . parent::getIdcart(), array('class' => 'btn btn-warning btn-mini'));
        } else {
            return link_to('wyłącz', 'cart/nopage?idcart=' . parent::getIdcart(), array('class' => 'btn btn-warning btn-mini'));
        }
    }

    public function getLocation()
    {
        switch (parent::getPosition()) {
            case 0:
                return 'górne menu';
                break;
            case 1:
                return 'dolne menu';
                break;
            case 2:
                return 'górne + dolne menu';
                break;
        }
    }

    public function getLinkBottom()
    {
        if (parent::getPosition() == 1 || parent::getPosition() == 2) {
            if (parent::getLinkActive() == 1) {
                return link_to('włącz', 'cart/linkactive?idcart=' . parent::getIdcart());
            } else {
                return link_to('wyłącz', 'cart/linkactive?idcart=' . parent::getIdcart());
            }
        }
    }

    public function getNumberWithAllPosition()
    {
        $cart = Doctrine_Core::getTable('Cart')
            ->createQuery('a')
            ->where('a.position = ?', parent::getPosition())
            ->count();

        if ($cart != 1) {
            return ($cart + 1);
        } else {
            return 1;
        }
    }

    public function getLinkUrl()
    {
        $sf_request = sfContext::getInstance()->getRequest();

        if (parent::getRedirectToUrl() != '') {
            return ($sf_request->getParameter('culture') ? '/' . $sf_request->getParameter('culture') : '') . parent::getRedirectToUrl();
        } else {
            return ($sf_request->getParameter('culture') ? '/' . $sf_request->getParameter('culture') : '')  . '/' . parent::getNameForLink() . '.html';
        }
    }

    public function hasActiveClass()
    {
        $sf_user = sfContext::getInstance()->getUser();

        if ($sf_user->getAttribute('cart_active') == parent::getIdcart()) {
            return 'active';
        }
    }
}
