<?php

/**
 * Configuration
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Configuration extends BaseConfiguration
{

    public static function getStringAndReplace($string = null)
    {
        $string_replace = str_replace(array('ą', 'ć', 'ę', 'ł', 'ń', 'ó', 'ś', 'ź', 'ż'), array('a', 'c', 'e', 'l', 'n', 'o', 's', 'z', 'z'), strtolower($string));
        $string_replace_next = str_replace(array('Ą', 'Ć', 'Ę', 'Ł', 'Ń', 'Ó', 'Ś', 'Ź', 'Ż'), array('a', 'c', 'e', 'l', 'n', 'o', 's', 'z', 'z'), $string_replace);
        $string_replace = str_replace(array('!', '?', '_', '.', ',', ':', '+', ' ', '', '', '„', '"', '---'), array('', '', '-', '', '', '', '', '-', '(', ')', '-', '' . '-'), $string_replace_next);
        $string_replace_de = str_replace(array('ä','ö','q','ß','ü','v','x','Ü'),array('a','o','q','b','u','v','x', 'u'),$string_replace);
        return strtolower($string_replace_de);
    }

    public static function getActive($name_option = null)
    {
        $configuration = Doctrine_Core::getTable('Configuration')->findOneBy('config_option', $name_option);

        if ($configuration) {
            if ($configuration->getConfigOn() == 1) {
                return true;
            }
        } else {
            return 'Brak zmiennej, uzupełnij konfiguracje!';

        }
    }

    public static function getOptionValue($option_name = null)
    {
        $configuration = Doctrine_Core::getTable('Configuration')->findOneBy('config_option', $option_name);
        if ($configuration) {
            if ($configuration->getConfigValue() != '') {
                return $configuration->getConfigValue();
            }
        } else {
            return 'Brak zmiennej, uzupełnij konfiguracje!';
            die;
        }
    }

    public static function getNameWithDayNumber($number)
    {
        $day_to_week = array();
        $day_to_week['1']['pl'] = 'poniedziałek';
        $day_to_week['2']['pl'] = 'wtorek';
        $day_to_week['3']['pl'] = 'środa';
        $day_to_week['4']['pl'] = 'czwartek';
        $day_to_week['5']['pl'] = 'piątek';
        $day_to_week['6']['pl'] = 'sobota';
        $day_to_week['7']['pl'] = 'niedziela';

        $day_to_week['1']['de'] = 'Montag';
        $day_to_week['2']['de'] = 'Dienstag';
        $day_to_week['3']['de'] = 'Mittwoch';
        $day_to_week['4']['de'] = 'Donnerstag';
        $day_to_week['5']['de'] = 'Freitag';
        $day_to_week['6']['de'] = 'Samstag';
        $day_to_week['7']['de'] = 'Sonntag';

        if (sfContext::getInstance()->getRequest()->getParameter('culture') == 'de') {
            return $day_to_week[$number]['de'];
        } else {
            return $day_to_week[$number]['pl'];
        }
    }

    function generateSeoURL($string)
    {
        $text = $string;

        $text = strtolower($text);

        $text = str_replace(' ', '-', $text);

        $text = preg_replace('/[^0-9a-z\-]+/', '', $text);

        $text = preg_replace('/[\-]+/', '-', $text);

        $text = trim($text, '-');

        return $text;
    }
}
