<?php

/**
 * DownloadCatalogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DownloadCatalogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DownloadCatalogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DownloadCatalog');
    }
}