<?php

/**
 * Download
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Download extends BaseDownload
{
    public function getLangTitle() {
        $bpcms_download_i18n = Doctrine_Core::getTable('BpcmsPageI18n')->createQuery('a')
                ->where('a.download_iddownload = ?', parent::getIddownload())
                ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
                ->fetchOne();

        if ($bpcms_download_i18n) {
            return $bpcms_download_i18n->getLangTitle() ? $bpcms_download_i18n->getLangTitle() : parent::getTitle();
        } else {
            return parent::getTitle();
        }
    }    
    
    public function getLinkToFile() {
        if(parent::getFileName() != '') {
            return '/uploads/files/'.parent::getFileName();
        } else {
            return parent::getUrlToFile();
        }
    }
}
