<?php

/**
 * Gallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Gallery extends BaseGallery {

    public function getSizePx() {
        list($width, $height) = getimagesize(sfConfig::get('sf_web_dir').'/images/gallery/'.parent::getFileName());
        
        return $width.'x'.$height;
    }

    public function getLangFileTitle() {
        $bpcms_gallery_i18n = Doctrine_Core::getTable('BpcmsGalleryI18n')->createQuery('a')
                ->where('a.gallery_idgallery = ?', parent::getIdgallery())
                ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
                ->fetchOne();

        if ($bpcms_gallery_i18n) {
            return $bpcms_gallery_i18n->getLangFileTitle() ? $bpcms_gallery_i18n->getLangFileTitle() : parent::getFileTitle();
        } else {
            return parent::getFileTitle();
        }
    }
}
