<?php

/**
 * GalleryCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GalleryCategory');
    }
}