<?php

/**
 * GalleryToPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryToPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryToPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GalleryToPage');
    }
}