<?php

/**
 * GalleryCatalogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryCatalogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryCatalogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GalleryCatalog');
    }
}