<?php

/**
 * GalleryToPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryToPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryToPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GalleryToPost');
    }
}