<?php

/**
 * MittendrinStatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MittendrinStatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MittendrinStatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MittendrinStats');
    }
}