<?php

/**
 * Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Page extends BasePage {

    public $culture;

    public function __toString() {
        return parent::getPageName();
    }

    public function getLangPageName() {
        $bpcms_page_i18n = Doctrine_Core::getTable('BpcmsPageI18n')->createQuery('a')
                ->where('a.page_idpage = ?', parent::getIdpage())
                ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
                ->fetchOne();

        if ($bpcms_page_i18n) {
            return $bpcms_page_i18n->getLangPageName() ? $bpcms_page_i18n->getLangPageName() : parent::getPageName();
        } else {
            return parent::getPageName();
        }
    }

    public function getNameForLink() {
        return Configuration::getStringAndReplace(self::getLangPageName());
    }

    public function getLangPageTitle() {
        $bpcms_page_i18n = Doctrine_Core::getTable('BpcmsPageI18n')->createQuery('a')
                ->where('a.page_idpage = ?', parent::getIdpage())
                ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
                ->fetchOne();

        if ($bpcms_page_i18n) {
            return $bpcms_page_i18n->getLangPageTitle() ? $bpcms_page_i18n->getLangPageTitle() : parent::getPageTitle();
        } else {
            return parent::getPageTitle();
        }
    }

    public function getLangPageBody() {
        $bpcms_page_i18n = Doctrine_Core::getTable('BpcmsPageI18n')->createQuery('a')
                ->where('a.page_idpage = ?', parent::getIdpage())
                ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
                ->fetchOne();

        if ($bpcms_page_i18n) {
            return $bpcms_page_i18n->getLangBody() ? $bpcms_page_i18n->getLangBody() : parent::getBody();
        } else {
            return parent::getBody();
        }
    }

    public function getLinkUrl()
    {
        $sf_request = sfContext::getInstance()->getRequest();

        if (parent::getRedirectToUrl() != '') {
            return ($sf_request->getParameter('culture') ? '/' . $sf_request->getParameter('culture') : '') . parent::getRedirectToUrl();
        } else {
            return ($sf_request->getParameter('culture') ? '/' . $sf_request->getParameter('culture') : '')  . '/' . parent::getNameForLink() . '.html';
        }
    }
}
