<?php

/**
 * PartnershipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartnershipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartnershipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partnership');
    }
}