<?php

/**
 * PostHasPostTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostHasPostTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostHasPostTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostHasPostTags');
    }
}