<?php

/**
 * PostTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostTags');
    }
}