<?php

/**
 * PostCatalogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostCatalogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostCatalogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostCatalog');
    }
}