<?php

/**
 * PostTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PostTags extends BasePostTags
{
    public function getSelected() {
        $sf_request = sfContext::getInstance()->getRequest();
        
        if($sf_request->getParameter('idpost')) {
            $post_has_post_tags = Doctrine_Core::getTable('PostHasPostTags')->find(array($sf_request->getParameter('idpost'), parent::getIdpostTags()));
            
            if($post_has_post_tags) {
                return 'checked="true"';
            }
        }
    }
}
