<?php

/**
 * RadioStationI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadioStationI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadioStationI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RadioStationI18n');
    }
}