<?php

/**
 * RadioStationScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadioStationScheduleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadioStationScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RadioStationSchedule');
    }
}