<?php

/**
 * RadioStationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadioStationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadioStationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RadioStation');
    }
}