<?php

/**
 * RadioStationScheduleI18nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadioStationScheduleI18nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadioStationScheduleI18nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RadioStationScheduleI18n');
    }
}