<?php

/**
 * RadioStationSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackcms
 * @subpackage model
 * @author     Damian Kania @ Eddi blackpage.pl 2012
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RadioStationSchedule extends BaseRadioStationSchedule
{
    public function getStatusPublication() {
        $status = new Status(parent::getPublication());

        return $status->getPublication();
    }

    public function getLangTitle()
    {
        $radio_station_schedule_i18n = Doctrine_Core::getTable('RadioStationScheduleI18n')->createQuery('a')
            ->where('a.radio_station_schedule_idradio_station_schedule = ?', parent::getIdradioStationSchedule())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($radio_station_schedule_i18n) {
            return $radio_station_schedule_i18n->getLangTitle() ? $radio_station_schedule_i18n->getLangTitle() : parent::getTitle();
        } else {
            return parent::getTitle();
        }
    }

    public function getLangDescription()
    {
        $radio_station_schedule_i18n = Doctrine_Core::getTable('RadioStationScheduleI18n')->createQuery('a')
            ->where('a.radio_station_schedule_idradio_station_schedule = ?', parent::getIdradioStationSchedule())
            ->andWhere('a.bpcms_lang_install_signature = ?', sfContext::getInstance()->getRequest()->getParameter('culture') ? sfContext::getInstance()->getRequest()->getParameter('culture') : sfContext::getInstance()->getUser()->getCulture())
            ->fetchOne();

        if ($radio_station_schedule_i18n) {
            return $radio_station_schedule_i18n->getLangDescription() ? $radio_station_schedule_i18n->getLangDescription() : parent::getDescription();
        } else {
            return parent::getDescription();
        }
    }
}
