<?php

/**
 * SlideshowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlideshowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlideshowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slideshow');
    }
}