SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `bpcms_page`.`cart` 
ADD COLUMN `position_row` VARCHAR(45) NULL DEFAULT NULL AFTER `redirect_to_url`;

ALTER TABLE `bpcms_page`.`page` 
ADD COLUMN `position_row` VARCHAR(45) NULL DEFAULT NULL AFTER `page_default`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
